### ISSUE TITLE
BANK  COULDN'T BE LOADED. Path incorrect or MasterBank not loaded yet.

### ISSUE THREAD

**Issue by starry-abyss** [utopia-rise/fmod-gdnative#108]
Hello! I've set up Fmod Studio 2.02.05 on openSUSE 15.3, Godot 3.4.2 and fmod-gdnative 3.1.1 (binary from github releases).

Playing a music as per low-level example in readme works great, however when it comes to loading banks as in the following example:

```
# set up FMOD
Fmod.set_software_format(0, Fmod.FMOD_SPEAKERMODE_STEREO, 0)
Fmod.init(1024, Fmod.FMOD_STUDIO_INIT_LIVEUPDATE, Fmod.FMOD_INIT_NORMAL)

# load banks
Fmod.load_bank("res://audio/fmod/Master.bank", Fmod.FMOD_STUDIO_LOAD_BANK_NORMAL)
Fmod.load_bank("res://audio/fmod/Master.strings.bank", Fmod.FMOD_STUDIO_LOAD_BANK_NORMAL)
```

I'm getting an error:

```
--- Debugging process started ---
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 660/PCIe/SSE2
OpenGL ES Batching: ON
 
Fmod Gdnative interface managed by a GDScript wrapper
FMOD Sound System: Successfully initialized
FMOD Sound System: Live update enabled!
Custom File System enabled.
FMOD Sound System: LOADING BANK res://audio/fmod/Master.bank
FMOD Sound System: BANK  COULDN'T BE LOADED. Path incorrect or MasterBank not loaded yet.
FMOD Sound System: LOADING BANK res://audio/fmod/Master.strings.bank
FMOD Sound System: BANK bank:/Master.strings LOADED
FMOD Sound System: System released
--- Debugging process stopped ---
```

Now I'm having a hard time trying to figure out what's wrong. I've tried to build the Master bank with and without an event assigned to it, and I've checked that Master bank is marked as the master bank. And I've checked that the bank file changes its size depending if it has an event assigned.

But I'm always getting this message...

Can you help me please?

**Comment by CedNaru** [comment]
Hello.
Try loading Master.strings.bank first and then Master.bank.
(and yes, I would need to change the examples in the docs if it's that)

**Comment by starry-abyss** [comment]
Yes, thank you for the fast response!

That was it, now I'm able to load the bank and play an event. :)

I guess I was also misled by "MasterBank not loaded yet", because I thought MasterBank was Master.bank, not Master.strings.bank. Not sure if the text is coming from FMOD itself and not the plugin though.
