### ISSUE TITLE
android build error "Activity cannot be converted to Godot"

### ISSUE THREAD

**Issue by sneekee-stache** [utopia-rise/fmod-gdnative#114]
hello
when i try to build my project for android i receive an error

 ```
Task :compileDebugJavaWithJavac FAILED
project/android/fmod/src/FmodSingleton.java:32: error: incompatible types: Activity cannot be converted to Godot

```
i had to add implementation instead of compile() and make my build.gradle immutable or else it would change the file back and tell me that there was no compile() methods.

**Comment by piiertho** [comment]
Hello !
What is your godot version ?

**Comment by sneekee-stache** [comment]
> Hello ! What is your godot version ?
godot 3.4.4

**Comment by piiertho** [comment]
@sneekee-stache can you try to replace `demo/android/fmod/src/FmodSingleton.java` by this one: https://github.com/utopia-rise/fmod-gdnative/blob/bugfix/android-export-plugin/demo/android/fmod/src/FmodSingleton.java ? To see if it fix it on your side

**Comment by sneekee-stache** [comment]
@piiertho it work, the project build itself but i don't have any sound playing on my phone, it play the sound on my pc tho.

**Comment by bitbrain** [comment]
@sneekee-stache @piiertho can this be closed?

**Comment by piiertho** [comment]
> @sneekee-stache @piiertho can this be closed?

No, not until https://github.com/utopia-rise/fmod-gdnative/pull/119 is merged.
