### ISSUE TITLE
Cannot load sounds or banks on windows x64

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/fmod-gdnative#3]
Application using GDNative crash when calling loadSound or loadBank methods.
The only information printed in console is : drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054.
In [godot-issue-27444](https://github.com/godotengine/godot/issues/27444) it is said that this error appears when debugger drop unexpectedly the app.
So for now we have no info about what is causing the bug.
We need to investigate what is crashing the app in the called methods.

**Comment by piiertho** [comment]
As we saw with @CedNaru, it seems that the error happens when finding in a  std::map. But it happens with fmodSoundConstants, fmodLoadBankFlags and does not happen with fmodInitFlags ans FmodStudioInitFlags. We still need to investigate about this behaviour specific on windows. Even if those maps will soon become useless.

**Comment by CedNaru** [comment]
I refactored the SConstruct file and somehow the dll now  #works on windows. Sounds play normally. 
[6416646](https://github.com/utopia-rise/fmod-gdnative/commit/641664681ccd8cd4cbc73910e2e3e247f45c3fc0) solves this issue.
