### ISSUE TITLE
No nativescript_init in libGodotFmod.windows.dll

### ISSUE THREAD

**Issue by HephepTeam** [utopia-rise/fmod-gdnative#41]
Hello,

I'm a total noob in GDNative so please tell me if I'm wrong opening this issue, first time for me. I tried to use the fmod-gdnative library you did, but I get this error when trying to run your demo project, here's what I did:

- Added the addons folders and all the subfolders to an existing project
- added libGodotFmod.windows.dll from the release tab, v2.0.2 in addons\fmod\lib\windows folder
(I got also those for osx and linux)
- removed some lines in the gdnlib file because I don't have this many platform to manage:

```
[general]

singleton=false
load_once=true
symbol_prefix="fmod_"
reloadable=true

[entry]

OSX.64="res://addons/fmod/libs/osx/libGodotFmod.osx.dylib"
Windows.64="res://addons/fmod/libs/windows/libGodotFmod.windows.dll"
X11.64="res://addons/fmod/libs/linux/libGodotFmod.linux.so"

[dependencies]

OSX.64=[  ]
Windows.64=[ "res://addons/fmod/libs/windows/libfmod.dll", "res://addons/fmod/libs/windows/libfmodstudio.dll" ]
X11.64=[  ]
```
- added the fmod API library file (took me a while to figure which one were needed, I took the dlls for x64 platform for my test, both core and studio, which are fmod.dll and fmodstudio.dll)
-copied the folders "scenes", "scripts" and "assets" from the demo project
Then I opened one of the two scenes and tried to run it. I tried both and I get the following error message every time:

```
ERROR: Can't open dynamic library: D:/GameDev/repo/test_3D/addons/fmod/libs/windows/libGodotFmod.windows.dll. Error: Error 126: Le module spécifié est introuvable.
   At: platform/windows/os_windows.cpp:2082
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:488
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1505
```

I checked through the source code and found this in gdlibrary.cpp:
```
extern "C" void GDN_EXPORT fmod_nativescript_init(void *handle){
    Godot::nativescript_init(handle);
    register_class<Fmod>();
}
```

and the symbol_prefix is set to "fmod_" in the gdnlib file so I don't see what's wrong, do you have a clue?

**Comment by piiertho** [comment]
Hi ! Readme is up to date with master branch. Change symbol_prefix to godot_ 2.0.2 code is still using old prefix [here](https://github.com/utopia-rise/fmod-gdnative/blob/v2.0.2/gdlibrary.cpp)

**Comment by HephepTeam** [comment]
Well since it doesn't work with only setting the symbol_prefix to "godot_", I will try compiling on my own. Do you have a deadline date or a rough estimate duration for the next release?

**Comment by piiertho** [comment]
@CedNaru when do you think it will be ok to merge branches ?
@HephepTeam which versions of FMOD and Godot do you use ?
Do you have same error ?

**Comment by HephepTeam** [comment]
Yes, same error about No nativescript_init, I didn't had the time this morning to get the full log it was just a quick test between breakfast and going to work. 
I use Godot 3.1.2 stable and the latest version for FMOD, I think it's 2.00.06

**Comment by piiertho** [comment]
Can you try with Godot 3.1.1, as specified in [godot compatibility matrix](https://github.com/utopia-rise/fmod-gdnative#godot-compatibility-matrix) and fmod 1.10.13 as specified in [fmod compatibility matrix](https://github.com/utopia-rise/fmod-gdnative#fmod-compatibility-matrix).
3.0.0 version of plugin will be up to date with godot 3.1.1 in a first time, and then with 3.2 when godot make the release. Also it will update fmod api version.
Master branch is using godot 3.1.1 and fmod 2.00.02.
Also you mentionned you place libraries in `addons\fmod\lib\windows` can you make sure the folder is `addons\fmod\libs\windows` and that fmod libraries are in same folder.

**Comment by HephepTeam** [comment]
I tried at work (don't tell my boss) with godot 3.1.1 stable, with FMOD API v1.10.13, and FMOD-GDNative v2.0.2. The path is right, sorry I misspelled it in my previous answer.Still the same error message:
```
OpenGL ES 3.0 Renderer: Intel(R) UHD Graphics 620
ERROR: load_image: Error opening file: C:/Users/michael.boyer/Downloads/tamanegi-nashi-master/assets/graphics/platform_phase/Nashi/stand/stand2.png
   At: core/io/image_loader.cpp:56
Editing project: C:/data/New folder/fmod-gdnative-master/demo (C:::data::New folder::fmod-gdnative-master::demo)
OpenGL ES 3.0 Renderer: Intel(R) UHD Graphics 620
ERROR: Can't open dynamic library: C:/data/New folder/fmod-gdnative-master/demo/addons/fmod/libs/windows/libGodotFmod.windows.dll. Error: Error 126: The specified module could not be found.

   At: platform/windows/os_windows.cpp:2082
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:488
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1501
erasing C:\Users\michael.boyer\AppData\Roaming/Godot/projects/demo-7366910ef8c977117a429b78da42e0a4/filesystem_update4
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:488
ERROR: terminate: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:393
ERROR: Can't open dynamic library: C:/data/New folder/fmod-gdnative-master/demo/addons/fmod/libs/windows/libGodotFmod.windows.dll. Error: Error 126: The specified module could not be found.

   At: platform/windows/os_windows.cpp:2082
Running: C:\Users\michael.boyer\Downloads\perso\Godot_v3.1-stable_win64.exe\Godot_v3.1.1-stable_win64.exe --path C:/data/New%20folder/fmod-gdnative-master/demo --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 122632 --position 448,240
OpenGL ES 3.0 Renderer: Intel(R) UHD Graphics 620
ERROR: Can't open dynamic library: C:/data/New folder/fmod-gdnative-master/demo/addons/fmod/libs/windows/libGodotFmod.windows.dll. Error: Error 126: The specified module could not be found.

   At: platform/windows/os_windows.cpp:2082
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:488
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1501
```

**Comment by piiertho** [comment]
Can you upload project so that I can try on lunch time ?

**Comment by HephepTeam** [comment]
Sure, here you go:
https://drive.google.com/file/d/1ot5s2-hJWY3X2idTIWtWnMAQ6zDK--LT/view?usp=sharing

(too big for github)
It's basically the demo project + 2.0.2 FMOD gdnative + FMOD API lib 1.10.13 (I hope it's the right files) and the gdnlib file symbol_prefix modified to "godot_"

Thanks you so much for your time!!

**Comment by piiertho** [comment]
It seems you don't have all libraries in folder, missing 64 librairies and statics one.
Also you should remove _vc suffix from the librairies you will add.
Here is the content of lib folder I have on my side:
![image](https://user-images.githubusercontent.com/48322356/72338076-fb3fb380-36c3-11ea-9e2a-5290c74bc3bc.png)
Also the class registered in gdnative is now called `Fmod` but in 2.0.2 it is still `GodotFmod`, so you need to modify gdns like that: 
```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://addons/fmod/Fmod.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "GodotFmod"
class_name = "GodotFmod"
library = ExtResource( 1 )
script_class_name = "FmodNative"
```

**Comment by HephepTeam** [comment]
Thanks @piiertho , I think I made a new step further. But now I need to adapt Fmod.gd because some function prototype don't have the same name. I'm digging in the API header files to find what could match. Currentlty I'm searching what was "set_listener_number" in API 10.0.13.

**Comment by piiertho** [comment]
Indeed, things has changed since 2.0.2. You can also compile driver from code for now. 1.x.x and 2.x.x versions were not supposed to be used in production.

**Comment by HephepTeam** [comment]
Hello, do you have some news about the next release? I couldn't achieve to compile the project yet.

**Comment by piiertho** [comment]
Hi !

Sorry, we're a bit late in our roadmap, we had a lot of work to do with godot-kotlin.
We should release this weekend, we only have to change the way android is built and adapt to godot 3.2 (should be done quite fast).

**Comment by HephepTeam** [comment]
Nice! Will it be compatible with Godot 3.1? I'm not planning to port my game to 3.2.

(I'll take a look at godot-kotlin I'm curious)

**Comment by piiertho** [comment]
We were planning only 3.2, but maybe we can make a last 3.1 release before adapting it. But it would be the last.

**Comment by HephepTeam** [comment]
Of course I understand. If you can make it it's cool, else I'll try compiling it again and I won't expect any support for this version don't worry !

**Comment by CedNaru** [comment]
Sorry it's taking time. The android compilation on windows doesn't work yet, I'm still trying to solve that issue without the use of a .mk file.

**Comment by atbigelow** [comment]
Just pinging if there was a Godot 3.2 compatible release planned soon? I could possibly get this thing to compile myself (I've got some experience with implementing FMOD Studio), but would rather not if it's soon.

**Comment by piiertho** [comment]
Hi ! We're late in our roadmap !
We have rollback android build to old ndk-build way. We still need to test on android and ios and then modify travis-ci.
If you only need windows/linux/macos, you can compile it yourself from master branch using godot-cpp vith 3.2 branch.
On our side we planned to work on FMOD during the weekend, but we're not sure everything will be finished, as we also have to work on godot-kotlin rework.
Sorry for being so late.

**Comment by CedNaru** [comment]
Hi.
We are currently testing if everything works the 3.2 update.
Windows, Linux and OSX are okay, we still more testing on Android/Ios (It's a lot of trouble because it's not really easy to deal with Gdnative with those platform). It should be released next week.

**Comment by atbigelow** [comment]
Thanks for the update! Can't wait to see the new release.

**Comment by piiertho** [comment]
Currently I got problems to resolve path on ios side. I got to manually add bank files to the app to get it work... And it seems we have the same problem on android. Maybe someone know how path works on those platforms ...

**Comment by piiertho** [comment]
Just an update. We managed to run fmod on godot 3.2 on all platforms (with assets files in application), we will create an issue on those, which is more related to how GDNative works.
CI is passing on the update branch, we still need to update documentation.
A release is coming when documentation is ready ! :P

**Comment by HephepTeam** [comment]
Great news, thanks!

**Comment by piiertho** [comment]
code is ready and builds well, but travis does not succeed to upload release ><

**Comment by HephepTeam** [comment]
Just wanted to let  you know, I got the demo project working perfectly on windows with FMOD 2.00.08 and Godot 3.2, thank you so much for you hard work!

**Comment by atbigelow** [comment]
I did as well. Thanks!

**Comment by piiertho** [comment]
thanks !

**Comment by apeyrard** [comment]
Hello,

I seem to have a similar problem on linux:

If i use your ligGodotFmod.linux.so i have those errors:

E 0:00:00.612   open_dynamic_library: Can't open dynamic library: /home/alex/limbic_realm/addons/fmod/libs/linux/libGodotFmod.linux.so. Error: libfmod.so.11: cannot open shared object file: No such file or directory
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  drivers/unix/os_unix.cpp:426 @ open_dynamic_library()
E 0:00:00.612   get_symbol: No valid library handle, can't get symbol from GDNative object
  <C++ Source>  modules/gdnative/gdnative.cpp:501 @ get_symbol()
E 0:00:00.612   init_library: No nativescript_init in "res://addons/fmod/libs/linux/libGodotFmod.linux.so" found
  <C++ Source>  modules/gdnative/nativescript/nativescript.cpp:1506 @ init_library()


If I compile your project with scons, and use that file in the addon folder, I can run the project in linux.
However, if I then try to export the project and then run it, I have those errors:

Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2

ERROR: open_dynamic_library: Can't open dynamic library: addons/fmod/libs/linux/libGodotFmod.linux.so. Error: libfmod.so.12: cannot open shared object file: No such file or directory
   At: drivers/unix/os_unix.cpp:426.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:501.
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/linux/libGodotFmod.linux.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.
SCRIPT ERROR: _init: Attempt to call function 'new' in base 'NativeScript' on a null instance.
   At: res://addons/fmod/Fmod.gdc:8.
SCRIPT ERROR: set_software_format: Invalid call. Nonexistent function 'set_software_format' in base 'Nil'.
   At: res://addons/fmod/Fmod.gdc:143.
SCRIPT ERROR: init: Invalid call. Nonexistent function 'init' in base 'Nil'.
   At: res://addons/fmod/Fmod.gdc:135.
SCRIPT ERROR: load_bank: Invalid call. Nonexistent function 'load_bank' in base 'Nil'.
   At: res://addons/fmod/Fmod.gdc:234.
SCRIPT ERROR: load_bank: Invalid call. Nonexistent function 'load_bank' in base 'Nil'.
   At: res://addons/fmod/Fmod.gdc:234.
SCRIPT ERROR: add_listener: Invalid call. Nonexistent function 'add_listener' in base 'Nil'.
   At: res://addons/fmod/Fmod.gdc:193.
SCRIPT ERROR: create_event_instance: Invalid call. Nonexistent function 'create_event_instance' in base 'Nil'.
   At: res://addons/fmod/Fmod.gdc:274.
SCRIPT ERROR: _ready: Invalid type in function 'start_event' in base 'Node (Fmod.gd)'. Cannot convert argument 1 from Nil to int.
   At: res://global_scripts/global.gdc:38.
The game runs, but there is no audio.

Is there something I am missing for the exports ? Here are the files in the export folder:

total 133M
-rw-r--r-- 1 alex alex  33M Jan 15 16:32 game.exe
-rw-r--r-- 1 alex alex 753K Jan 15 16:32 libGodotFmod.windows.release.64.dll
-rw-r--r-- 1 alex alex 1.5M Jan 15 16:32 fmod.dll
-rw-r--r-- 1 alex alex 968K Jan 15 16:32 fmodstudio.dll
-rwxr-xr-x 1 alex alex  41M Jan 15 16:56 game.x86_64
-rw-r--r-- 1 alex alex  48M Jan 15 16:56 game.pck
-rw-r--r-- 1 alex alex 5.3M Jan 15 16:56 libGodotFmod.linux.so
-rw-r--r-- 1 alex alex 1.6M Jan 15 16:56 libfmod.so
-rw-r--r-- 1 alex alex 1.6M Jan 15 16:56 libfmodstudio.so

Thank you

**Comment by piiertho** [comment]
Hey @apeyrard !  
This is fixed in https://github.com/utopia-rise/fmod-gdnative/commit/c5170ec99771b35b9eec8e02e00f313e648e942e  
Can you try this modification ?  
BTW next time can you open a new issue ?
It is pretty hard to manage conversations in closed issues.

**Comment by apeyrard** [comment]
Hello @piiertho,
Sorry for the late answer, I encountered a bug that took time to troubleshoot and was also related to audio.

I'll also make sure to open a new issue next time.

Anyway, everything works well now.
Thanks for you work on this repository, it is really helpful !
