### ISSUE TITLE
Is setup (wiki) outdated?

### ISSUE THREAD

**Issue by TandersT** [utopia-rise/fmod-gdnative#44]
Following the current wiki, I encounter an error with GDNative:

E 0:00:00.814   open_dynamic_library: Can't open dynamic library: C:/Users/Stefan/source/godot/fmod-intergration/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 127: The specified procedure could not be found.

.
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  platform/windows/os_windows.cpp:2269 @ open_dynamic_library()

I've tried following the guide given in the readme, but I suppose it's a bit over my head trying to built the C++ bindings. But alas, the guide in the wiki seem to indicate building bindings etc. is uneeded, but it does not seem to work.

**Comment by piiertho** [comment]
Hi there ! It should work using releases.
Can you show the content of `addons/fmod/libs/windows/` folder please ?

**Comment by TandersT** [comment]
Of course,
Current Godot version: v3.2.1
GDNative version: v3.0.0
FMod: 2.01.00
[windows folder](https://i.imgur.com/CuVyzo4.png)

**Comment by piiertho** [comment]
Really weird, this works on my side. Can you provide a demo to reproduce it ? I'd like to look at project structure to get insights.

**Comment by TandersT** [comment]
Sure I haven't changed anything in the demo project, other than adding the needed libraries.
Here's the project:
https://send.firefox.com/download/b233109bd8b203cb/#eiFOWtYdcVUwoTCzPT-rtA


Here's the entire log, from opening project till pressing play:

Mono: Logfile is: C:\Users\Stefan\AppData\Roaming/Godot/mono/mono_logs/2020_05_13 15.23.34 (11992).txt
ERROR: Can't open dynamic library: C:/Users/Stefan/source/godot/fmod-intergration/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 127: The specified procedure could not be found.
.
   At: platform/windows/os_windows.cpp:2269
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506
WARNING: _get: EditorSettings::_get - Property not found: mono/editor/editor_path_optional
     At: editor/editor_settings.cpp:151
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483
ERROR: terminate: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:388
ERROR: Can't open dynamic library: C:/Users/Stefan/source/godot/fmod-intergration/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 127: The specified procedure could not be found.
.
   At: platform/windows/os_windows.cpp:2269
Running: C:\Program Files\Godot_v3.2.1\Godot_v3.2.1.exe --path C:/Users/Stefan/source/godot/fmod-intergration --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 11992 --position 448,240
Godot Engine v3.2.1.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 2070/PCIe/SSE2

Mono: Logfile is: C:\Users\Stefan\AppData\Roaming/Godot/mono/mono_logs/2020_05_13 15.23.43 (18144).txt
ERROR: Can't open dynamic library: C:/Users/Stefan/source/godot/fmod-intergration/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 127: The specified procedure could not be found.
.
   At: platform/windows/os_windows.cpp:2269
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506

Seems as if the error happens as soon as the project is opened.

As for permissions, are you referring to permission for SYSTEM? Or something else?
These are the permission for SYSTEM
https://imgur.com/1sRA4OD

**Comment by piiertho** [comment]
Oh ! I got it, I did not read well you fmod version.
[here](https://github.com/utopia-rise/fmod-gdnative#fmod-compatibility-matrix) you have the compatibility matrix.
They are some link changes in 2.01.XX, please try it with 2.00.XX.

**Comment by TandersT** [comment]
Hi, no issue, I should have caught that myself! Changed to version 2.00.09 and it works right out the box!
Thanks for the help.
