### ISSUE TITLE
Nullptr Bug

### ISSUE THREAD

**Issue by dogwind** [utopia-rise/fmod-gdnative#45]
I got a bug that occurs after using FMOD.shutdown() and later reinitializing it. The functionality stops working and this error is printed:

`ERROR: void __cdecl godot::Fmod::_process(float): A socket error occurred.  This is a catch-all for socket-related errors not listed elsewhere.`

I looked into the shutdown implementation and the following seemed odd: 

In godot_fmod.cpp shouldn't:

`    system = nullptr;`
`    coreSystem = nullptr;`
`    ERROR_CHECK(system->unloadAll());`
`    ERROR_CHECK(system->release());`

be this:

`    ERROR_CHECK(system->unloadAll());`
`    ERROR_CHECK(system->release());`
`    coreSystem = nullptr;`
`    system = nullptr;`

I recompiled the libraries and the error spam stopped, so it seems like it fixed something.

**Comment by piiertho** [comment]
Oops Yep, you're right !
It seems to be an attention mistake. 
Do you want to PR it or should I do it ?
