### ISSUE TITLE
need video tutorial

### ISSUE THREAD

**Issue by q531620267** [utopia-rise/fmod-gdnative#48]
Hello, can you do a teaching video to demonstrate how Fmod and Godot interact? I'm new to both of them. I downloaded the demo, but I can't open the project file in the demo folder with Godot. I really want to learn Fmod and Godot integration, but I can't practice it. Thank you for your answer.

**Comment by CedNaru** [comment]
I have no experience in making videos so this request is a bit too much for me as I don't even know where to start to make one. Even if I could do, it would only be about how you can use FMOD from within Godot. I wouldn't make a video explaining how Godot and Fmod both work separately There are many well-done resources for that already. 

For now, the integration is very simple, we only exposed Fmod API and made it available in GDScript, the main page of this repo has a bunch of examples already and the practical use is not much different from them.
It all depends on how well you already mastered Godot and Fmod, our bindings are just a simple glue code to make them bot communicate.
 You said you were not able to open the demo folder. So what I can do is improving the setup guide by adding more explanations and more screenshots. What do you think about that?

**Comment by q531620267** [comment]
> 我没有制作视频的经验，所以这个要求对我来说有点过了，因为我甚至不知道从哪里开始制作一个视频。即使我能做到，这也只是关于如何从戈多内部使用FMOD。我不会制作一段视频来解释戈多和FMOD是如何分开工作的，已经有很多做得很好的资源了。
> 
> 目前，集成非常简单，我们只公开了FmodAPI并在GDScript中提供了它，这个回购的主页已经有了大量的例子，实际使用与它们没有太大的不同。
> 这一切都取决于你已经很好地掌握了戈多和Fmod，我们的绑定只是一个简单的胶水代码，以使他们的机器人沟通。
> 你说你不能打开演示文件夹。因此，我能做的是通过添加更多的解释和更多的屏幕截图来改进设置指南。你觉得怎么样？

It would be great to have a screenshot tutorial. I just need to use the Godot engine to open your demo and there will be no error reporting, so as to learn it a little bit. Thank you for your contribution and improvement to the project, which will help more new people like me to learn.

**Comment by q531620267** [comment]
https://streamable.com/7qy0ok

**Comment by q531620267** [comment]
> https://streamable.com/7qy0ok

this video show i cant open it.

**Comment by q531620267** [comment]
> I have no experience in making videos so this request is a bit too much for me as I don't even know where to start to make one. Even if I could do, it would only be about how you can use FMOD from within Godot. I wouldn't make a video explaining how Godot and Fmod both work separately There are many well-done resources for that already.
> 
> For now, the integration is very simple, we only exposed Fmod API and made it available in GDScript, the main page of this repo has a bunch of examples already and the practical use is not much different from them.
> It all depends on how well you already mastered Godot and Fmod, our bindings are just a simple glue code to make them bot communicate.
> You said you were not able to open the demo folder. So what I can do is improving the setup guide by adding more explanations and more screenshots. What do you think about that?

It would be great to have a screenshot tutorial. I just need to use the Godot engine to open your demo and there will be no error reporting, so as to learn it a little bit. Thank you for your contribution and improvement to the project, which will help more new people like me to learn.

**Comment by piiertho** [comment]
Jeu ! Did you add fmod librairies to your project ? We cannot distribute fmod code as it is not opensource, so you have to add libraries on your own

**Comment by q531620267** [comment]
> Hey ! Did you add fmod librairies to your project ? We cannot distribute fmod code as it is not opensource, so you have to add libraries on your own

I'm sorry I didn't do this. I just downloaded the Fmod studio API windows. Its directory structure is API, bin, DOC and plugins. Which one is Fmod libraries?

**Comment by piiertho** [comment]
You should follow this part of readme
https://github.com/utopia-rise/fmod-gdnative#add-fmod-libraries-to-appropriate-folder
IIRC librairies are in api subfolder. Look at README and find DLL in it.

**Comment by q531620267** [comment]
> You should follow this part of readme
> https://github.com/utopia-rise/fmod-gdnative#add-fmod-libraries-to-appropriate-folder
> IIRC librairies are in api subfolder. Look at README and find DLL in it.

ok,think you very much!
