### ISSUE TITLE
Exported project cannot find banks, oggs and events?

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/fmod-gdnative#49]
**OS:** Windows 10
**Godot:** v3.2.3
**Fmod:** 2.00.14

I'm playing around with the demo project and tried to export it to an EXE. 
In the editor everything works fine without any issue, but when I run my exported build I get these errors:

![error](https://user-images.githubusercontent.com/42484461/99152638-41c6bb80-26a3-11eb-9e04-a5f2781cb62c.PNG)

I checked my .PCK with the [godot-unpacker](https://github.com/tehskai/godot-unpacker) and found that indeed the necessary files are available, as shown here:
![image](https://user-images.githubusercontent.com/42484461/99152701-a2ee8f00-26a3-11eb-8e39-07e6f741de35.png)

I'm using the demo-project included inside of this repo and I'm using the latest release DLL for windows x64. Also I'm using the 2.00 version of both fmod.DLL and fmodstudio.DLL.

How do I make an exported build work properly?

**Comment by 2shady4u** [comment]
Small addendum/update: If I copy the assets folder next to the exported EXE. Everything works...
However, Fmod should be able to use the banks and ogg that are present in the PCK instead? 🤔

**Comment by piiertho** [comment]
Hey @2shady4u !
Thank you for the bug report.
It seems we are not managing ressource path properly.
I think problematic code is here:
https://github.com/utopia-rise/fmod-gdnative/blob/6c71f3f030243836e7ac177ee981690ecccddd08/src/godot_fmod.h#L20
Maybe we will have difficulty to pass ressource path to fmod. IIRC we had a discussion with @CedNaru few months ago about this.

**Comment by 2shady4u** [comment]
I think I had a similar issue with calling the inklecate.exe on exported builds.
In that case I fixed it by always extending the path to a global path using this function:

```
static func get_game_folder() -> String:
	if OS.has_feature("standalone"):
		print("Running an exported build.")
		return OS.get_executable_path().get_base_dir()
	else:
		print("Running from the editor.")
		return ProjectSettings.globalize_path("res://")
```

Maybe this is a good work-around for the time being?

**Comment by CedNaru** [comment]
Having the files next to the .exe is how I proceed.
That plugin is just a bridge to FMOD, so FMOD itself can't access files the same way Godot does. 
Using "res://" paths for FMOD object are renamed to standard relative paths, It's just a trick I added so people are able to unify the path, but maybe it wasn't a good idea because it can be confusing.
At it is today, I don't know how I can read inside a PCK file from Fmod.

**Comment by CedNaru** [comment]
One possibility I see:
-Godot File object seems to give enough control to the reading of the File with function such as "get_buffer", 'seek".
-I never used that, but it seems that you can implement some custom File callback system for FMOD.

By using those 2 functionalities, it might be possible to implement some fallback system in the plugin that would directly interact with a Godot File Object if Fmod can't directly access it.

**Comment by CedNaru** [comment]
Link:
[Fmod File Callback ](https://www.fmod.com/resources/documentation-api?version=2.1&page=core-api-system.html#system_setfilesystem)
[Godot File](https://docs.godotengine.org/en/3.0/classes/class_file.html)

**Comment by 2shady4u** [comment]
@CedNaru @piiertho 
@fire was able to make it work for the SQLite module here:
https://github.com/godot-extended-libraries/godot-sqlite/blob/a9b699c90203989239c49eebbfc70c11fc2ac59c/sqlite.cpp#L185
(using the open_buffered()-function)

But I didn't go deeper into it so I don't know how it exactly works... But it involves the use of this particular file:
https://github.com/godot-extended-libraries/godot-sqlite/blob/master/thirdparty/sqlite/spmemvfs.h

@CedNaru Yes, having the files next to the EXE works, so I'll use that method for now.

**Comment by fire** [comment]
Feel free to ask any questions.

**Comment by fire** [comment]
I don't remember much but here's a more recent pointer. https://github.com/godot-extended-libraries/godot-sqlite/blob/master/sqlite.cpp#L218

**Comment by BrianMWest** [comment]
Is anyone actively working this one? I ran into this issue and can use the workaround for now, but will need a more robust solution at some point. If no one else is able to get to it, I may be able to devote some time on it once I've addressed the more urgent tickets for my game, but it'll probably be a bit before then

**Comment by piiertho** [comment]
@BrianMWest for now we did not started to work on this issue. Feel free to contribute :)
Anyway this issue needs to be resolved. We would work on it when kotlin is alpha, but if someone have time we're opened to contribs :D
