### ISSUE TITLE
Issue build Android platform

### ISSUE THREAD

**Issue by beelzeebub** [utopia-rise/fmod-gdnative#51]
I have issue when build Android platform.

![2020-12-16_155738](https://user-images.githubusercontent.com/26085384/102327019-b4cf9480-3fb7-11eb-84e7-a11a2e77a77d.png)

**Comment by piiertho** [comment]
Hello !
Can you provide more informations, like your project structure, what steps did you made to produce the error, what is your `ANDROID_NDK_ROOT` ?
Only a screenshot will not be enought to help you.

**Comment by beelzeebub** [comment]
I have export AnDROID_NDK_ROOT, this is my struct folder, same guideline. 
I build command : scons platform=android generate_bindings=True android_arch=armv7 target=debug
Build successful, issue when linker
![image](https://user-images.githubusercontent.com/26085384/102339724-2c0d2480-3fc8-11eb-8e24-afcd55cd8385.png)

**Comment by piiertho** [comment]
Did you use official godot-cpp pour the one we provide in readme ?
Also what is `ANDROID_NDK_ROOT` value on your side ?
Paths seems weird in your screenshot.

**Comment by beelzeebub** [comment]
Thank you for support me. I build on Ubutu 20.4
**I had checkout godot-cpp branch 3.2**
![image](https://user-images.githubusercontent.com/26085384/102436911-25c08c00-404c-11eb-9afc-479ba20a0903.png)
**This is my ANDROID_NDK_ROOT path**
![image](https://user-images.githubusercontent.com/26085384/102436955-3d981000-404c-11eb-811d-50dba9de02b4.png)
**This my struct folder project:**
![image](https://user-images.githubusercontent.com/26085384/102437041-6ae4be00-404c-11eb-975a-9800b236cf4c.png)
**I had build successful godot-cpp**:
![image](https://user-images.githubusercontent.com/26085384/102437179-b303e080-404c-11eb-86cb-6091e57b207e.png)
**When build fmod-gdnative have error:**
![image](https://user-images.githubusercontent.com/26085384/102437244-d0d14580-404c-11eb-8d86-b572e3cf5bd4.png)

**Comment by piiertho** [comment]
Sorry for late answer.  
Can you try with ndk-build ? Our scons does not works well with android, we use classic ndk for now.  
https://github.com/utopia-rise/fmod-gdnative#android-1

**Comment by beelzeebub** [comment]
Thank you for support. I had build successfull with ndk-build
