### ISSUE TITLE
Using a Node as a listener crashes the game without errors

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/fmod-gdnative#60]
According to the function definition `add_listener()` expects an Integer and a Node.
However, when calling the `add_listener()`-function and using a Node as the second argument, the game just quits/crashes?
Everything works fine if the listener is a Node2D, Spatial or Control.

Example with Node (CRASHES):
![node](https://user-images.githubusercontent.com/42484461/105067701-43847500-5a80-11eb-9aab-36e23d2f15c9.gif)

Example with Spatial:
![spatial](https://user-images.githubusercontent.com/42484461/105067595-20f25c00-5a80-11eb-9c29-236cfa552ca4.gif)

In both cases the Godot console doesn't show any errors:
![Capture](https://user-images.githubusercontent.com/42484461/105067794-6151da00-5a80-11eb-88ab-a82d8cda304c.PNG)

Also in a similar vein, when looking at the C++ source code, I can see that the `addListener()`-function (to which the `add_listener()`-function in Godot is bound) expects an **Object** instead of a **Node**? This kind of implicit casting (from Node to Object) feels dangerous? (I could be mistaken?) Also what could be the use of, for example, making a Resource (which inherits from Object) a listener? I do think all these Objects in the source code should actually just be Nodes instead?

**Comment by 2shady4u** [comment]
I'm also unsure if the examples in the README.md actually work? Because the listeners all seem to be Nodes :/

**Comment by piiertho** [comment]
Thanks for the bug catching.  
[Here](https://github.com/utopia-rise/fmod-gdnative/blob/e9e70cd64d7681568fe0776d8d3423f87fe16955/src/godot_fmod.cpp#L283) is the piece of code that cause problem (I think).  
There should be a check using `isFmodValid` [here](https://github.com/utopia-rise/fmod-gdnative/blob/e9e70cd64d7681568fe0776d8d3423f87fe16955/src/godot_fmod.cpp#L406), with an error log is condition is not meet.

**Comment by CedNaru** [comment]
Yes, we need to add a check when we attach a node to a listener.
Sadly we can let you set a simple Node as a listener. Fmod requires a position, which we can only get from Node2D or Spatial.

**Comment by CedNaru** [comment]
Regarding the Object Parameter, it's true that the first common ancestor is Node, not Object. I guess we can change that.
It depends if we have more classes outside of Node2D and Spatial (and child classes) that have a position property. Otherwise no object to changing it.

**Comment by 2shady4u** [comment]
Yes, at least some kind of error message would be nice.

Most of my confusion comes from the fact that all the examples in the README.md use `extends Node`. Which made me assume that I could use Nodes as listeners. I do know that you can add scripts that extend Node to Spatials, Node2Ds, etc... and that those scripts are thus perfectly valid in those cases. 🤔 

PS: @CedNaru Please don't forget about my boys, the Control nodes!

**Comment by CedNaru** [comment]
Ha yeah Sorry. I meant CanvasItem, not Node2D.
I always forget which one is the parent class.
