### ISSUE TITLE
SUGGESTION: make Fmod autoload singleton a Node (Fmod.tscn)

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/fmod-gdnative#61]
Due to the nature of my game, I would like the Fmod autoload singleton to not be paused when I pause the game.
For example I have different sliders: master volume, music volume, sfx volume, .... that are linked to specific FMOD busses.

Currently the following happens:
- Play some FMOD event
- Pause the game, the event keeps playing (= ok)
- Change the volume -> nothing happens
- Unpause the game, the volume function finally gets called (because Fmod.gd was paused) and volume decreases

This behaviour is a bit counter-intuitive...
This happens because the Fmod autoload singleton derives from a script and not from a PackedScene.

**My suggestion:**
Change the `Fmod.gd` autoload singleton to a `PackedScene `instead.
This `PackedScene `then gets the `Fmod.gd`-scripts but has the added bonus of having the `pause_mode`-variable available and the user can either set to this to `inherited `or `process` (whatever he wants)

**Comment by CedNaru** [comment]
I think I have tried at first to make it a scene so it's easier to configure some stuff. But if I remember correctly, I met a bug that prevented me to properly load a scene as an autoload or something similar.
If this properly works in the current stable version of Godot, I agree to this change as it was something I also wanted.
