### ISSUE TITLE
Can't get the addon working on Windows, Error: "Can't open dynamic library"

### ISSUE THREAD

**Issue by imjp94** [utopia-rise/fmod-gdnative#68]
OS: Windows 10
Godot: 3.2.3-stable
Driver: v3.0.2
Fmod API: 2.00.15
Minimal project: [fmod-test.zip](https://github.com/utopia-rise/fmod-gdnative/files/5878279/fmod-test.zip)

Output:
> modules/gdnative/gdnative.cpp:501 - No valid library handle, can't get symbol from GDNative object
> modules/gdnative/gdnative.cpp:406 - No valid library handle, can't terminate GDNative object
> Can't open dynamic library: D:/Godot/fmod-test/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 193: %1 is not a valid Win32 application.

Debugger:
> E 0:00:00.306   open_dynamic_library: Can't open dynamic library: D:/Godot/fmod-test/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 193: %1 is not a valid Win32 application.
.
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  platform/windows/os_windows.cpp:2395 @ open_dynamic_library()

> E 0:00:00.309   get_symbol: No valid library handle, can't get symbol from GDNative object
  <C++ Source>  modules/gdnative/gdnative.cpp:501 @ get_symbol()

> E 0:00:00.313   init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll" found
  <C++ Source>  modules/gdnative/nativescript/nativescript.cpp:1506 @ init_library()

**Comment by CedNaru** [comment]
I managed to find the root issue.
I replace the different fmod.dll in your project with mine.
Your issues is because of the file names. 
Just delete the regular fmod.dll/fmodstudio.dl and rename fmod64.dll/fmodstudio64.dll by fmod.dll/fmodstudio.dll.

I am a bit confused by this one. The 64 bits dll I got from the fmod website don't have the 64 suffixes so I don't need to rename them in the first place.

**Comment by imjp94** [comment]
Thanks, It works now!

My bad, I was totally clueless when setup the driver.
I thought libs/windows must be the same as [screenshot in issue 41](https://github.com/utopia-rise/fmod-gdnative/issues/41#issuecomment-574117157), so I copy dlls from both x64 & x86 fmod api folders and rename one of it with 64 suffixes.
Now it make sense...

**Comment by CedNaru** [comment]
Sorry for this screenshot if it was confusing, it was just our own folder for when we were testing multiple builds so it was not properly orgarnized.
