### ISSUE TITLE
No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll" found

### ISSUE THREAD

**Issue by apeyrard** [utopia-rise/fmod-gdnative#69]
Hello,

While I don't have this issue on linux anymore, I still have it on windows.
Here is what I did, and the versions I used:

fmod version : 2.00.08 (Because someone said this one worked in the other nativescript issue. I also tried the latest version)
Godot version: 3.2.3
fmod-gdnative version: 13213a4

In windows 10:

I generated the api.json file, as detailed in the godot-cpp documentation.
I went into godot-cpp and built it with this command:
 scons platform=windows generate_bindings=yes use_custom_api_file=yes custom_api_file=api.json target=release

Modified the Sconstruct file to remove the expected _vc suffix from the libraries, since this suffix wasnt present in my files.
I went into fmod-gdnative and built it with this command:
 scons platform=windows target=release bits=64

Copied all the files to addons/fmod/libs/windows
Here is my folder: 
[windows.zip](https://github.com/utopia-rise/fmod-gdnative/files/5887600/windows.zip)
I did not find librairies named fmod64 and fmodstudio64 as said in issue https://github.com/utopia-rise/fmod-gdnative/issues/41, so I guess the naming scheme changed since then. Those libraries are from the x64 folder of fmod librairies.

When trying to run the project, I have those errors (edited to remove my name, but otherwise as is):

```
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2

Running project: C:/Users/<name>/Desktop/dev/limbic_island (C:::Users::<name>::Desktop::dev::limbic_island)
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2

ERROR: Can't open dynamic library: C:/Users/<name>/Desktop/dev/limbic_island/addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll, error: Error 126: The specified module could not be found.
.
   At: platform/windows/os_windows.cpp:2395
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:501
ERROR: init_library: No nativescript_init in "res://addons/fmod/libs/windows/libGodotFmod.windows.release.64.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506
SCRIPT ERROR: _init: Attempt to call function 'new' in base 'NativeScript' on a null instance.
          At: res://addons/fmod/Fmod.gd:122
SCRIPT ERROR: set_software_format: Invalid call. Nonexistent function 'set_software_format' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:155
SCRIPT ERROR: init: Invalid call. Nonexistent function 'init' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:142
SCRIPT ERROR: load_bank: Invalid call. Nonexistent function 'load_bank' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:246
SCRIPT ERROR: load_bank: Invalid call. Nonexistent function 'load_bank' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:246
### here
[Node:1184]
SCRIPT ERROR: add_listener: Invalid call. Nonexistent function 'add_listener' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:205
SCRIPT ERROR: create_event_instance: Invalid call. Nonexistent function 'create_event_instance' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:286
SCRIPT ERROR: _ready: Invalid type in function 'start_event' in base 'Node (Fmod.gd)'. Cannot convert argument 1 from Nil to int.
          At: res://global_scripts/global.gd:38
SCRIPT ERROR: _notification: Invalid call. Nonexistent function 'free' in base 'Nil'.
          At: res://addons/fmod/Fmod.gd:133
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:501
ERROR: terminate: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:406

```
Is there something I am doing wrong ?
Thank you

**Comment by CedNaru** [comment]
Are you sure you really took the fmod.dll from the x64 folder ? 
I used the window.zip you sent and yes, it doesn't work.
But if I replace the fmod.dll/fmodstudio.dll with mine, it properly works. 
Your dlls have a size that match the 32 bits version of mine. So maybe you just made a mistake ?

**Comment by apeyrard** [comment]
That's strange, I checked again and can't find a mistake, the size of my files matches the 64 bit version.
Here's a screenshot comparing them all:
![lib_size](https://user-images.githubusercontent.com/2933254/106158635-db1e4d80-617b-11eb-9184-6f77e6ca2f84.PNG)

What's your version of fmod ?

**Comment by CedNaru** [comment]
I don't remember the version I have on my computer, it's basically the same one I had since we started this project.
I think it was 2.00.02. But a minor version change should still be fully compatible.

**Comment by apeyrard** [comment]
Hello,

The issue was that I was downloading and using the "Windows 10 UWP" installer from Fmod instead of the simple windows installer, and using the libraries from that wrong installer.

Now that I'm using the right one, everything is working.

Thank you for your help.
