### ISSUE TITLE
Fix compilation flags for Linux

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/fmod-gdnative#72]
Linux compiled library is HUGE (40MB 😱 ) in comparison to other platforms.
Seems like this is due to the fact that some flags are missing/wrong

Here's the relevant part of a modified SConstruct that creates library with smaller sizes:
![image](https://user-images.githubusercontent.com/42484461/106888645-276f0d80-66e7-11eb-9573-d7241bc00a23.png)
(As found [here](https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/native/SConstruct))

Differences are:
- We dont have the LINKFLAG -s
- We have an additional CCFLAG in release mode -g

Implementing these changes should give a linux library that is a bit lesser in size...

**Comment by CedNaru** [comment]
I don't mind those changes. 
We just took a basic Scontruct example for Gdnative and adapted what we needed to for Android and IOS but didn't change the flags for other platforms.

**Comment by CedNaru** [comment]
By the way, if you have any hints to reduce the size of the IOS lib, I would gladly take them :p

**Comment by piiertho** [comment]
For iOS size is big because we have armv7 and armv8 in same lib. Dont know if you changed this in your github actions PR @2shady4u ?

**Comment by 2shady4u** [comment]
@piiertho @CedNaru  Currently the Github Actions only compiles for arm64 and it's still humongous (80MB)

![unknown](https://user-images.githubusercontent.com/42484461/107028357-be060200-67ad-11eb-9680-7446d4b750c6.png)

^ that's the latest artifacts from the Github Actions branch.

Can I recommend checking out the original godot-cpp repository? And updating the utopia-rise godot-cpp fork as a result.
Because with the latest godot-cpp I seem to be getting much smaller iOS sizes:

![image](https://user-images.githubusercontent.com/42484461/107029468-581a7a00-67af-11eb-8182-d86e2f2a82a3.png)

Also there have been numerous critical fixes merged recently (memory leakage, etc...)

**Comment by piiertho** [comment]
Yep, iOS support is much more better than in our fork in official. Will rebase on it this we so that we can check

**Comment by 2shady4u** [comment]
This has been implemented in #62
