### ISSUE TITLE
Demo project throws errors in Godot v3.3 RC8

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/fmod-gdnative#79]
If opening the demo-project in Godot v3.3 RC8, you get swamped with errors:
```
ERROR: Request for nonexistent InputMap action 'kill_event'.
   At: main/input_default.cpp:110
ERROR: Request for nonexistent InputMap action 'rotate_right'.
   At: main/input_default.cpp:102
ERROR: Request for nonexistent InputMap action 'rotate_left'.
```

Opening in Godot v3.2.3:
![version3 2 3](https://user-images.githubusercontent.com/42484461/114224167-063dce00-9971-11eb-80ab-7e4b09fabd29.PNG)

Opening in Godot v3.3 RC8:
![version3 3](https://user-images.githubusercontent.com/42484461/114224171-08079180-9971-11eb-8421-b1f8b2d6f9c0.PNG)

Seems that these actions either have to be properly defined OR the relevant input code that calls these actions has to be removed.
Are these missing actions, leftovers that have to be removed? or are they just missing?

**Comment by CedNaru** [comment]
I think that might just be me forgetting to commit one fil of the project. So the key binds have never been saved.
