### ISSUE TITLE
Noob-friendly how-to 

### ISSUE THREAD

**Issue by nicolasGab** [utopia-rise/fmod-gdnative#80]
Hi,

First of all, thank you for the work you've done on this project. I'm very interested in integrating Fmod in my current Godot project but I'm having a hard time achieving anything with the current `README` instructions. I feel like they are written for people with prior experience with Godot submodules and GDNative. Would you consider writing noob-friendly, step-by-step instructions?

**Comment by CedNaru** [comment]
I think the main issue is the emphasis we put on the building /compiling part of this project.
When you are a simple end-user, you don't need to do all those steps. Only the "Installing the GDNative in your project" is necessary.
I propose that we move the compiling section into its own separate pages so you can immediately see the part that matters for end users and rewrite the part that explains how to get the necessary files and how to install them in your own project.

**Comment by piiertho** [comment]
I totally agree, readme is not straightforward

**Comment by IntangibleMatter** [comment]
How is this issue almost a year old? I've been struggling with this too and it would take at most an hour to solve.

**Comment by piiertho** [comment]
@nicolasGab and @IntangibleMatter can you tell me if it is better with #111 ?
