### ISSUE TITLE
Error when following setup and importing demo project

### ISSUE THREAD

**Issue by bitbrain** [utopia-rise/fmod-gdnative#82]
I have followed the instructions in the README and installed the FMOD Windows API from here:

![Capture2](https://user-images.githubusercontent.com/822035/137575496-f4bcfb44-f315-4b40-b499-9d9c569c8f5f.JPG)
 I then proceeded, searching for the `*.dll` files and copied them over into the `addons/fmod/libs/windows` folder as suggested:
![Capture3](https://user-images.githubusercontent.com/822035/137575506-6db75f86-8a19-4ff7-ab9c-962aba8065ab.JPG)
However, when importing the demo project I get this nasty error:
![Capture](https://user-images.githubusercontent.com/822035/137575531-7c069701-27a2-4be1-8da1-16294c0a2a0c.JPG)

Does anybody know what mistake I did?

I used fmod-gdnative `v3.0.2` from the Releases tab and Godot v3.3.4.stable

**Comment by bitbrain** [comment]
@piiertho looks like this was resolved with https://github.com/utopia-rise/fmod-gdnative/commit/c701073b9f6809d2a934d8f43486d9ca46c2d1af

**Comment by 2shady4u** [comment]
Solved in #88
